### ISSUE TITLE
Action does not fail if permissions are not set correctly

### ISSUE THREAD

**Issue by rajbos** [devops-actions/issue-comment-tag#193]
You'll need to specify the permissions if you have limited them somewhere:
``` yaml
permissions:
  issues: write
  pull-requests: write
```

If you do not, the action will not fail, but also will not do anything (and thus seems broken)
